# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

#monitor=,preferred,auto,1,mirror,eDP-1
# Syntax: monitor=name,resolution@hz,position,scale
# ==--==--==--==--==--==--==--==--==--==--==--== #

$CONFIGS = ~/.config/hypr/configs

source = $CONFIGS/environ.conf
source = $CONFIGS/exec.conf
source = $CONFIGS/binds.conf
source = $CONFIGS/settings.conf
source = $CONFIGS/animations.conf
source = $CONFIGS/rules.conf

source = /home/dhruxy-_-/.config/hypr/noctalia/noctalia-colors.conf

