# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/
# ==--==--==--==--==--==--==--==--==--==--==--== #
$PATH = ~/.config/hypr
$CONFIGS = $PATH/configs 

source = $PATH/monitors.conf
source = $PATH/workspaces.conf

source = $CONFIGS/environ.conf 
source = $CONFIGS/exec.conf
source = $CONFIGS/binds.conf
source = $CONFIGS/settings.conf
source = $CONFIGS/animations.conf
source = $CONFIGS/rules.conf

source = $PATH/noctalia/noctalia-colors.conf
