# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

monitor=eDP-1,2560x1600@90.00100,0x0,1.33
#monitor=,preferred,auto,1,mirror,eDP-1
# Syntax: monitor=name,resolution@hz,position,scale
monitor=HDMI-A-1, 1920x1080@60, auto, 0.83
# ==--==--==--==--==--==--==--==--==--==--==--== #

$CONFIGS = ~/.config/hypr/configs

source = $CONFIGS/environ.conf
source = $CONFIGS/exec.conf
source = $CONFIGS/binds.conf
source = $CONFIGS/settings.conf
source = $CONFIGS/animations.conf
source = $CONFIGS/rules.conf

source = /home/dhruxy-_-/.config/hypr/noctalia/noctalia-colors.conf

