general.import = [ "~/.config/alacritty/theme.toml" ]
[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font"  # change to your font
style = "Regular"

[window]
padding.x = 0
padding.y = 0
decorations = "None"
opacity = 1.0
startup_mode = "Fullscreen"

[scrolling]
history = 0
